name: systemMonitor CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtest-dev

      - name: Add CMake to system path
        run: echo "export PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV

      - name: Create build directory
        run: |
          cd CppND-System-Monitor-Project
          mkdir build

      - name: Run cmake then make
        run: |
          cd CppND-System-Monitor-Project/build
          cmake ..
          make

      - name: Run tests
        run: |
          cd CppND-System-Monitor-Project/build/test
          make test --rerun-failed --output-on-failure
          cat /home/runner/work/Udacity_Cpp_nanodegree/Udacity_Cpp_nanodegree/CppND-System-Monitor-Project/build/test/Testing/Temporary/LastTest.log