name: systemMonitor CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1

      - name: Build project
        run: |
          cd Udacity_Cpp_nanodegree/CppND-System-Monitor-Project/build
          make

      - name: Run tests
        run: |
          cd Udacity_Cpp_nanodegree/CppND-System-Monitor-Project/build
          make test